describe('Form', () => {
  before(() => cy.exec('rm -rf cypress/screenshots'))
  beforeEach(() => cy.visit('../../formulario.html'))
  // it('Formulario', () => {
  //   cy.visit('../../formulario.html')
  // })
  it.only('', () => {
    cy.get('#nome').as('name').type('Denis')
    cy.get('#sobrenome').as('lastName').type('Coelho')
    cy.get('#email').as('email').type('denis@email.com')
    cy.get('input[type="radio"][value="fullstack"]')
      .as('fullstackRadio')
      .check()
    cy.get('#senioridade').as('seniority').select('Sênior')
    cy.get('input[type="checkbox"][value="HTML"]')
      .as('htmlCheckBox')
      .check()
    cy.get('input[type="checkbox"][value="CSS"]')
      .as('cssCheckBox')
      .check()
    cy.get('input[type="checkbox"][value="Javascript"]')
      .as('jsCheckBox')
      .check()
    cy.screenshot('antes-de-submeter-form')
    cy.get('.botao').click()

    cy.get('@name').should('be.empty')
    cy.get('@lastName').should('be.empty')
    cy.get('@email').should('be.empty')
    cy.get('@fullstackRadio').should('not.be.checked')
    cy.get('input[type="radio"][value="frontend"]').should(
      'be.checked'
    )
    cy.get('@seniority')
      .find('option')
      .contains('Selecione')
      .should('be.selected')
    cy.get('@htmlCheckBox').should('not.be.checked')
    cy.get('@cssCheckBox').should('not.be.checked')
    cy.get('@jsCheckBox').should('not.be.checked')
    cy.screenshot('depois-de-submeter-form')
  })
})
